spring.application.name=expense-tracker-api

logging.level.com.app.expense.config=error

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true


# Allow all origins to access the OpenAPI JSON (v3/api-docs)
springdoc.api-docs.enabled=true
springdoc.api-docs.groups.enabled=true

# Specifically for the OpenAPI Spec endpoint
springdoc.cors.allowed-origins=*
springdoc.cors.allowed-methods=GET, POST, OPTIONS

# Change the path of the JSON spec if you want
springdoc.api-docs.path=/api-docs

# Disable the built-in Swagger UI if you are using your own HTML file
springdoc.swagger-ui.enabled=false


